spring.application.name=jobTracker
#Port configuration
server.port=8080

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/jobTrackerDB
spring.datasource.username=postgres
spring.datasource.password=Pubg@47929
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secretKey = maepfmaofmcapwfoapadoamdapowmd2019-3i210-4931@_#!)#_!